# Generated by Django 5.1.7 on 2025-04-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant_list", "0002_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="keywords",
        ),
        migrations.RemoveField(
            model_name="review",
            name="sentiment_score",
        ),
        migrations.RemoveField(
            model_name="review",
            name="source",
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.FloatField(),
        ),
    ]
